---
title: "Beyond Research"
description: ""
---

## My Science Journey in a Nutshell

Upon graduationg university, I had the opportunity to explore different fields of science from agriculture and food technology to nanochemistry and radiology - all these because I was trying to find my passion. Before coming to the US to pursue my interest in microbiome research, I served for two years as a frontliner in a COVID-19 diagnostic laboratory in the Philippines (toughest of times). My experience in different fields have taught me to be motivated by collaborative science, thoughtful study design, and research that directly impacts patients and communities.

## A Bit More About Me

I'm originally from the Philippines and thus still prefer hot summers over cold winters.

When I'm not in scientist mode, you can find me:

-   🌍 Exploring Cleveland and nearby states
-   🎾 Playing tennis (trying, at least)
-   📚 Reading self-help books

## Book Recommendations

I like self-help books because it makes me reflect on myself and gain insight on how to be a better person for me and those around me. I rarely read fiction. Here are my top five recommended books (as of October 2025).

-   ["Mastery"](https://medium.com/@robertgreene/the-path-to-mastery-32d3d4d495a4) by Robert Greene
-   ["The Courage to Be Disliked"](https://www.goodreads.com/book/show/43306206-the-courage-to-be-disliked) by Ichiro Kishimi
-   ["How Do You Live?"](https://www.goodreads.com/book/show/54110592-how-do-you-live) by Genzaburo Yoshino
-   ["Educated"](https://tarawestover.com/book_=) by Tara Westover
-   ["Some People Need Killing: A Memoir of Murder in My Country"](https://www.penguinrandomhouse.com/books/612869/some-people-need-killing-by-patricia-evangelista/) by Patricia Evangelista

## 
